// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NasaAPI.Context;

namespace NasaAPI.Migrations
{
    [DbContext(typeof(ContextoDB))]
    [Migration("20220720111545_MigracionInicial")]
    partial class MigracionInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NasaAPI.Models.Meteorito", b =>
                {
                    b.Property<string>("_nombre")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("_diametro")
                        .HasColumnType("real");

                    b.Property<string>("_fecha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_planeta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_velocidad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("_nombre");

                    b.ToTable("Meteoritos");
                });
#pragma warning restore 612, 618
        }
    }
}
